"""add_simple_model

Revision ID: 49a0ca8b9e39
Revises: 0291bfa086eb
Create Date: 2024-09-20 19:28:09.855553

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "49a0ca8b9e39"
down_revision = "0291bfa086eb"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "simple_models",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("simple_models")
    # ### end Alembic commands ###
