version: '3.8'

services:
  nginx:
    image: nginx:latest
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "81:81"
    networks:
      - articles-service
    depends_on:
      - articles

  articles:
    build:
      context: .
      dockerfile: Dockerfile
    command: gunicorn --bind 0.0.0.0:8001 --workers 4 'articles.app:create_app()' --reload
    volumes:
      - ./:/articles-service
    ports:
      - "8001:8001"
    networks:
      articles-service:
        aliases:
          - articles-app

volumes:
  nginx:

networks:
  articles-service:
